"""
Wellness service.

Not in the original v0 PRD scope -- added after, alongside auth. Serves
two things: diet/exercise content, and a directory of nearby providers
(yoga instructors, dietitians, psychiatrists, counsellors).

Compliance boundary, stated plainly because it's the one thing in this
module that's easy to get wrong under time pressure: content and provider
matches are keyed on postpartum STAGE and REGION only, never on a
mother's clinical_events. The moment this filters by "what's due" or "what
condition she has," it stops being a content library and starts being a
treatment recommendation -- which is one of the six things the event's
scope rules exclude (see docs/compliance.md, "Treatment recommendations").
Do not add a woman_id parameter to either endpoint below that changes what
comes back. If personalization is ever wanted, that's a v1+ conversation
with whoever owns compliance sign-off, not a quick addition here.

All content is seeded, fixed text with a source_citation -- never
generated by a model, same rule as ruleset.yaml's citations (Rule 3: "no
generated clinical text").

Still stubbed: this is a static seed list, not a real content database or
a live "nearby" geolocation search. Region is a flat string match, not a
map. Good enough to demo, not to ship.
"""
from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional
import uuid

router = APIRouter()


class WellnessContent(BaseModel):
    id: str
    type: str
    stage: str
    region: str
    title: str
    body: str
    source_citation: str


class Provider(BaseModel):
    id: str
    name: str
    type: str
    region: str
    language: str
    gender: str
    contact: str


_CONTENT: list[dict] = [
    WellnessContent(
        id=str(uuid.uuid4()),
        type="diet",
        stage="postpartum_early",
        region="general",
        title="Iron-rich foods in the first weeks",
        body="Leafy greens, jaggery, and lentils help rebuild iron after "
             "delivery, especially if blood loss was significant. Pair "
             "iron-rich foods with a source of vitamin C, like citrus or "
             "tomato, to help absorption.",
        source_citation="VERIFY -- national postpartum nutrition guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()),
        type="diet",
        stage="postpartum_early",
        region="kerala",
        title="Kerala postpartum diet -- what still holds up",
        body="Warm, easily digested foods like rice kanji and ghee-based "
             "preparations are traditional in the first weeks and are "
             "broadly consistent with current nutrition guidance for "
             "recovery. Extreme restriction of vegetables or fruits for "
             "the full confinement period is not supported by current "
             "guidance and can be safely relaxed.",
        source_citation="VERIFY -- regional dietary guidance, cross-checked against ICMR (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()),
        type="diet",
        stage="postpartum_early",
        region="punjab",
        title="Punjab postpartum diet -- what still holds up",
        body="Ghee, whole grains and panjeeri (a dry-fruit and gum-resin "
             "mix) are traditional postpartum foods and are calorie- and "
             "nutrient-dense, which is broadly appropriate during "
             "recovery and breastfeeding. Portion size matters more than "
             "avoidance here -- check with a dietitian if you have "
             "gestational diabetes.",
        source_citation="VERIFY -- regional dietary guidance, cross-checked against ICMR (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()),
        type="exercise",
        stage="postpartum_early",
        region="general",
        title="Gentle movement in the first six weeks",
        body="Short, slow walks and gentle breathing exercises are "
             "generally safe from the first week for an uncomplicated "
             "vaginal delivery. After a caesarean, wait for your "
             "six-week review before starting anything beyond walking, "
             "and always check with your provider first.",
        source_citation="VERIFY -- FOGSI postpartum activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()),
        type="exercise",
        stage="postpartum_six_week",
        region="general",
        title="Pelvic floor exercises after the six-week check",
        body="Once cleared at your six-week review, gentle pelvic floor "
             "exercises (Kegels) can help with recovery. Start slowly and "
             "stop if you notice pain or heaviness -- check with a "
             "physiotherapist if either happens.",
        source_citation="VERIFY -- FOGSI postpartum activity guidance (draft placeholder)",
    ).model_dump(),
]

_PROVIDERS: list[dict] = [
    Provider(
        id=str(uuid.uuid4()), name="Dr. Lakshmi Rao", type="psychiatrist",
        region="andhra_pradesh", language="te", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="Priya Nair", type="counsellor",
        region="kerala", language="ml", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="Anjali Kumar", type="dietitian",
        region="general", language="en", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="Ritu Sharma", type="yoga",
        region="punjab", language="pa", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="Dr. Sunita Reddy", type="psychiatrist",
        region="general", language="en", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
]


@router.get("/content")
def get_content(stage: Optional[str] = None, region: Optional[str] = None):
    results = _CONTENT
    if stage:
        results = [c for c in results if c["stage"] == stage]
    if region:
        results = [c for c in results if c["region"] in (region, "general")]
    return {"content": results}


@router.get("/providers")
def get_providers(type: Optional[str] = None, region: Optional[str] = None, language: Optional[str] = None):
    results = _PROVIDERS
    if type:
        results = [p for p in results if p["type"] == type]
    if region:
        results = [p for p in results if p["region"] in (region, "general")]
    if language:
        results = [p for p in results if p["language"] == language]
    return {"providers": results}
