"""
Wellness service.

Not in the original v0 PRD scope -- added after, alongside auth. Serves
diet/exercise/hydration content, a directory of nearby providers (yoga
instructors, dietitians, psychiatrists, counsellors, gyms), and two
things she sets herself: taste preferences and a saved plan.

Compliance boundary, stated plainly because it's the one thing in this
module that's easy to get wrong under time pressure: content and provider
matches are keyed on postpartum STAGE and REGION only, never on a
mother's clinical_events. The moment this filters by "what's due" or "what
condition she has," it stops being a content library and starts being a
treatment recommendation -- which is one of the six things the event's
scope rules exclude (see docs/compliance.md, "Treatment recommendations").
Do not add a woman_id parameter to get_content or get_providers that
changes what comes back based on her clinical history. If personalization
by condition is ever wanted, that's a v1+ conversation with whoever owns
compliance sign-off, not a quick addition here.

nutrients on a WellnessContent item are FACTS ABOUT THE FOOD (calories,
protein, fiber, iron, calcium) -- never a personalised target computed
for her ("you need X because of Y"). That distinction is what keeps this
a nutrition label instead of a prescription.

taste_tags, _TASTE_PREFS and _SAVED_PLANS are all HER OWN choices --
she sets a taste preference, she saves an item she liked. Nothing here is
inferred from her record. This is what makes the plan "hers" without the
system deciding for her.

All content is seeded, fixed text with a source_citation -- never
generated by a model, same rule as ruleset.yaml's citations (Rule 3: "no
generated clinical text").

Still stubbed: this is a static seed list, not a real content database or
a live "nearby" geolocation search. Region is a flat string match, not a
map. Good enough to demo, not to ship.
"""
from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional
from datetime import datetime, timezone
import uuid

router = APIRouter()


class Nutrients(BaseModel):
    """Facts about the food itself. Never a personalised target -- that
    would be a clinical recommendation, not a nutrition fact."""
    calories: Optional[int] = None
    protein_g: Optional[float] = None
    fiber_g: Optional[float] = None
    iron_mg: Optional[float] = None
    calcium_mg: Optional[float] = None


class WellnessContent(BaseModel):
    id: str
    type: str  # "diet" | "exercise" | "hydration"
    subtype: Optional[str] = None  # exercise: walking|pelvic_floor|pilates|gym|cardio
    stage: str
    region: str
    title: str
    body: str
    avoid_notes: Optional[str] = None  # diet only: what to avoid at this stage
    nutrients: Optional[Nutrients] = None  # diet only
    taste_tags: list[str] = []  # vegetarian, spicy, mild, regional cuisine names etc.
    source_citation: str


class Provider(BaseModel):
    id: str
    name: str
    type: str  # "yoga" | "dietitian" | "psychiatrist" | "counsellor" | "gym"
    region: str
    language: str
    gender: str
    contact: str


class TastePreference(BaseModel):
    woman_id: str
    tags: list[str] = []  # vegetarian, spicy, mild, regional names, dislikes (prefixed "avoid:")


_CONTENT: list[dict] = [
    WellnessContent(
        id=str(uuid.uuid4()),
        type="diet",
        stage="postpartum_early",
        region="general",
        title="Iron-rich foods in the first weeks",
        body="Leafy greens, jaggery, and lentils help rebuild iron after "
             "delivery, especially if blood loss was significant. Pair "
             "iron-rich foods with a source of vitamin C, like citrus or "
             "tomato, to help absorption.",
        nutrients=Nutrients(calories=180, protein_g=8, fiber_g=6, iron_mg=4.5, calcium_mg=90).model_dump(),
        taste_tags=["vegetarian"],
        source_citation="VERIFY -- national postpartum nutrition guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()),
        type="diet",
        stage="postpartum_early",
        region="kerala",
        title="Kerala postpartum diet -- what still holds up",
        body="Warm, easily digested foods like rice kanji and ghee-based "
             "preparations are traditional in the first weeks and are "
             "broadly consistent with current nutrition guidance for "
             "recovery. Extreme restriction of vegetables or fruits for "
             "the full confinement period is not supported by current "
             "guidance and can be safely relaxed.",
        avoid_notes="Full confinement-period restriction of vegetables and fruits is not "
                     "necessary and can be safely relaxed.",
        nutrients=Nutrients(calories=220, protein_g=5, fiber_g=3).model_dump(),
        taste_tags=["mild", "vegetarian", "regional:kerala"],
        source_citation="VERIFY -- regional dietary guidance, cross-checked against ICMR (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()),
        type="diet",
        stage="postpartum_early",
        region="punjab",
        title="Punjab postpartum diet -- what still holds up",
        body="Ghee, whole grains and panjeeri (a dry-fruit and gum-resin "
             "mix) are traditional postpartum foods and are calorie- and "
             "nutrient-dense, which is broadly appropriate during "
             "recovery and breastfeeding. Portion size matters more than "
             "avoidance here -- check with a dietitian if you have "
             "gestational diabetes.",
        avoid_notes="Large portions can be more calorie-dense than needed -- moderate portion "
                     "size, especially if managing gestational diabetes.",
        nutrients=Nutrients(calories=310, protein_g=9, fiber_g=4, calcium_mg=60).model_dump(),
        taste_tags=["vegetarian", "regional:punjab"],
        source_citation="VERIFY -- regional dietary guidance, cross-checked against ICMR (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()),
        type="exercise",
        subtype="walking",
        stage="postpartum_early",
        region="general",
        title="Gentle movement in the first six weeks",
        body="Short, slow walks and gentle breathing exercises are "
             "generally safe from the first week for an uncomplicated "
             "vaginal delivery. After a caesarean, wait for your "
             "six-week review before starting anything beyond walking, "
             "and always check with your provider first.",
        source_citation="VERIFY -- FOGSI postpartum activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()),
        type="exercise",
        subtype="pelvic_floor",
        stage="postpartum_six_week",
        region="general",
        title="Pelvic floor exercises after the six-week check",
        body="Once cleared at your six-week review, gentle pelvic floor "
             "exercises (Kegels) can help with recovery. Start slowly and "
             "stop if you notice pain or heaviness -- check with a "
             "physiotherapist if either happens.",
        source_citation="VERIFY -- FOGSI postpartum activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="hydration", stage="postpartum_early", region="general",
        title="Fluids in the first weeks",
        body="Water, buttermilk, and clear soups through the day help with milk supply and "
             "general recovery. Aim to drink whenever you feel thirsty rather than waiting; "
             "breastfeeding increases fluid needs noticeably.",
        avoid_notes="Very sugary drinks are best kept occasional, since they can crowd out "
                     "more useful fluids.",
        source_citation="VERIFY -- national postpartum nutrition guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="diet", stage="pregnancy_t1", region="general",
        title="First trimester -- nausea-friendly foods",
        body="Small, frequent meals with plain, mild foods (rice, khichdi, dry toast) are often "
             "easier to keep down than large or spicy meals.",
        avoid_notes="Very oily or strongly spiced food can worsen nausea for some women -- this "
                     "varies person to person.",
        nutrients=Nutrients(calories=250, protein_g=6, fiber_g=2).model_dump(),
        taste_tags=["mild", "vegetarian"],
        source_citation="VERIFY -- national antenatal nutrition guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="diet", stage="pregnancy_t3", region="general",
        title="Third trimester -- iron and calcium focus",
        body="Leafy greens, dairy or a calcium-rich alternative, and iron-rich pulses become more "
             "important as the third trimester progresses.",
        avoid_notes="Unpasteurised dairy and undercooked meat or eggs are best avoided.",
        nutrients=Nutrients(calories=350, protein_g=14, fiber_g=5, iron_mg=6, calcium_mg=200).model_dump(),
        taste_tags=["vegetarian"],
        source_citation="VERIFY -- national antenatal nutrition guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="diet", stage="pregnancy_t2", region="general",
        title="Second trimester -- steady, balanced meals",
        body="Regular meals with pulses, vegetables, fruit and grains help meet the extra energy "
             "needs of the middle months.",
        avoid_notes="Unpasteurised dairy and undercooked meat or eggs are best avoided.",
        nutrients=Nutrients(calories=300, protein_g=10, fiber_g=4, iron_mg=4, calcium_mg=150).model_dump(),
        taste_tags=["vegetarian"],
        source_citation="VERIFY -- national antenatal nutrition guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="exercise", subtype="pelvic_floor", stage="postpartum_six_week",
        region="general", title="Pelvic floor basics",
        body="Gentle Kegel exercises, a few times a day, once cleared at your six-week review.",
        source_citation="VERIFY -- FOGSI postpartum activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="exercise", subtype="cardio", stage="postpartum_six_week",
        region="general", title="Easing into cardio",
        body="Brisk walking or light cycling, starting short and building up gradually, once "
             "cleared at your six-week review.",
        source_citation="VERIFY -- FOGSI postpartum activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="exercise", subtype="pilates", stage="postpartum_six_week",
        region="general", title="Beginner postnatal pilates",
        body="Core-focused, low-impact movement suitable once cleared at your six-week review -- "
             "look for a class specifically labelled postnatal.",
        source_citation="VERIFY -- FOGSI postpartum activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="exercise", subtype="gym", stage="postpartum_long",
        region="general", title="Returning to the gym",
        body="Once cleared and comfortable with walking and pelvic floor work, a gradual return "
             "to light resistance training is generally appropriate for most women.",
        source_citation="VERIFY -- FOGSI postpartum activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="diet", stage="postpartum_six_week", region="general",
        title="Weeks 6 to 26 -- steady, balanced meals",
        body="Regular meals with pulses, vegetables, fruit, grains and enough fluids. If you are "
             "breastfeeding, you may feel hungrier than usual and need extra fluids.",
        avoid_notes="Very little to avoid for most women; ask your doctor if unsure.",
        nutrients=Nutrients(calories=300, protein_g=10, fiber_g=4, iron_mg=4, calcium_mg=150).model_dump(),
        taste_tags=["vegetarian"],
        source_citation="VERIFY -- national postpartum nutrition guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="diet", stage="postpartum_long", region="general",
        title="After six months -- everyday balanced eating",
        body="A varied plate with pulses, vegetables, fruit, grains and dairy or a calcium-rich "
             "alternative supports recovery and energy in the longer term.",
        avoid_notes="Ask your doctor if you are unsure about any food.",
        nutrients=Nutrients(calories=250, protein_g=8, fiber_g=4, iron_mg=3, calcium_mg=120).model_dump(),
        taste_tags=["vegetarian"],
        source_citation="VERIFY -- national postpartum nutrition guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="exercise", subtype="walking", stage="pregnancy_t1",
        region="general", title="First trimester -- gentle walking",
        body="Easy walking at a comfortable pace is a common way to stay active early in pregnancy. "
             "Check with your doctor before starting any new exercise.",
        source_citation="VERIFY -- national antenatal activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="exercise", subtype="pilates", stage="pregnancy_t2",
        region="general", title="Second trimester -- prenatal yoga or pilates",
        body="Look for classes specifically labelled prenatal and tell the instructor you are "
             "pregnant. Check with your doctor before joining.",
        source_citation="VERIFY -- national antenatal activity guidance (draft placeholder)",
    ).model_dump(),
    WellnessContent(
        id=str(uuid.uuid4()), type="exercise", subtype="walking", stage="pregnancy_t3",
        region="general", title="Third trimester -- gentle movement",
        body="Short walks, prenatal stretching and breathing exercises at an easy pace. Slow down "
             "or stop if something feels wrong, and check with your doctor.",
        source_citation="VERIFY -- national antenatal activity guidance (draft placeholder)",
    ).model_dump(),
]

_PROVIDERS: list[dict] = [
    Provider(
        id=str(uuid.uuid4()), name="Dr. Lakshmi Rao", type="psychiatrist",
        region="andhra_pradesh", language="te", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="Priya Nair", type="counsellor",
        region="kerala", language="ml", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="Anjali Kumar", type="dietitian",
        region="general", language="en", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="Ritu Sharma", type="yoga",
        region="punjab", language="pa", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="Dr. Sunita Reddy", type="psychiatrist",
        region="general", language="en", gender="female",
        contact="VERIFY -- placeholder contact, not a real clinician",
    ).model_dump(),
    Provider(
        id=str(uuid.uuid4()), name="FitLife Women's Gym", type="gym",
        region="general", language="en", gender="female",
        contact="VERIFY -- placeholder contact, not a real business",
    ).model_dump(),
]

# In-memory stores for her own choices -- neither is inferred from
# clinical_events, both are things SHE sets.
_TASTE_PREFS: dict[str, list[str]] = {}       # woman_id -> tags
_SAVED_PLANS: dict[str, list[dict]] = {}      # woman_id -> [{content_id, saved_at}]


@router.get("/content")
def get_content(stage: Optional[str] = None, region: Optional[str] = None):
    results = _CONTENT
    if stage:
        results = [c for c in results if c["stage"] == stage]
    if region:
        results = [c for c in results if c["region"] in (region, "general")]
    return {"content": results}


@router.get("/providers")
def get_providers(type: Optional[str] = None, region: Optional[str] = None, language: Optional[str] = None):
    results = _PROVIDERS
    if type:
        results = [p for p in results if p["type"] == type]
    if region:
        results = [p for p in results if p["region"] in (region, "general")]
    if language:
        results = [p for p in results if p["language"] == language]
    return {"providers": results}


@router.post("/taste-preference")
def set_taste_preference(pref: TastePreference):
    """Overwrites her tag list -- she sets this herself, not inferred from
    anything else in her record."""
    _TASTE_PREFS[pref.woman_id] = pref.tags
    return {"woman_id": pref.woman_id, "tags": pref.tags}


@router.get("/taste-preference/{woman_id}")
def get_taste_preference(woman_id: str):
    return {"woman_id": woman_id, "tags": _TASTE_PREFS.get(woman_id, [])}


@router.post("/saved-plan/{woman_id}/{content_id}")
def save_to_plan(woman_id: str, content_id: str):
    """She adds an item she found in the library to her own plan. This is
    what makes the plan 'hers' -- her choice, not a system recommendation."""
    entry = {"content_id": content_id, "saved_at": datetime.now(timezone.utc).isoformat()}
    _SAVED_PLANS.setdefault(woman_id, []).append(entry)
    return {"status": "saved", "entry": entry}


@router.get("/saved-plan/{woman_id}")
def get_saved_plan(woman_id: str):
    """Returns her saved items with the full content attached, so the
    frontend doesn't need a second round trip."""
    saved = _SAVED_PLANS.get(woman_id, [])
    by_id = {c["id"]: c for c in _CONTENT}
    items = [dict(by_id[s["content_id"]], saved_at=s["saved_at"])
             for s in saved if s["content_id"] in by_id]
    return {"items": items}


@router.delete("/saved-plan/{woman_id}/{content_id}")
def remove_from_plan(woman_id: str, content_id: str):
    _SAVED_PLANS[woman_id] = [s for s in _SAVED_PLANS.get(woman_id, []) if s["content_id"] != content_id]
    return {"status": "removed"}